### PR TITLE
Allow requires_context to accept any value for a slot

### PR DESCRIPTION
**Pull request by tetele**

### CODE REVIEW

**Comment by tetele** [comment]
@balloob and @synesthesiam regarding [this](https://github.com/home-assistant/intents/issues/575#issuecomment-1379764085) and [this](https://github.com/home-assistant/intents/pull/608#issuecomment-1380662972), maybe you guys want to look at my proposal above. Thanks!

I can't specifically ask for a review on this repo.

**Comment by synesthesiam** [comment]
I'll wait to review until after the merging of the cover intents :+1:

**Comment by tetele** [comment]
I don't see a reason to refactor this purely because of the cover intents merge, but let me know what you think @synesthesiam. Thanks!

**Comment by synesthesiam** [comment]
Thanks!

**Pull request merged**
