### PR TITLE
Add fuzzy matching using edit distance

### PR DESCRIPTION
**Pull request by synesthesiam**
Add an optional "edit budget" to intent recognition to allow for fuzzy matching.

When text matching fails on a chunk of text, the number of edits required to force them to match is computed and added to the "cost" of the match. If this cost exceeds the budget, the match is discarded.

Some complexity is required when deciding how to compare the text chunk with the remaining text to be matched. If the text chunk is "turn " and the remaining text is "trn on the light", we just want the edit distance between "turn" and "trn". To accomplish this, we start at the index equal to the length of the text chunk and walk backwards until we find a word boundary (space). So we start at "trn [o]n the light" in this case, and end up using this word boundary: "trn[ ]on the light".

### CODE REVIEW

**Comment by tetele** [comment]
I'm not sure that's the intended use case, but I think this would work fabulously if you first convert text to phonemes for both STT transcript and accepted sentences. 💡

**Comment by synesthesiam** [comment]
That would be awesome to do, and would certainly work much better than operating in the text domain. [gruut](https://github.com/rhasspy/gruut) could be used to do this in the future for some languages.

**Comment by synesthesiam** [comment]
Another idea would be to do a pure Python implementation of espeak-ng's pronunciation algorithm: https://github.com/espeak-ng/espeak-ng/blob/master/docs/dictionary.md

**Comment by X-Ryl669** [comment]
@synesthesiam I'm just discovery the realm of all your projects and I'm amazed. You've worked on fuzzywuzzy, NLU for rhasspy, so you probably have a lot of experience on those algorithms. 

I'm currently reading the source code for Hassil but it seems it's either a lot simpler than Rhasspy or I'm missing some things.

Can you confirm how Hassil is processing the intents? Right now, I've the feeling that it's processing them in O(N), dismissing those that don't fit. I've read that you've used a graph in the past before (which should be a lot faster, in O(log N) IIUC).

I've implemented a C++ fuzzy ternary search tree with Levenshtein and partial match, and while it worked very well on quite good formatted text, I wonder it'll end up completely wrong on a STT output (since as you said, there isn't any 1:1 matching on a textual representation and a sound).

As far as I understand it, it seems we are making the work a lot harder by trying to match in textual world. Since we have speech, maybe a speech to phoneme (or equivalent) would match a lot easier with phoneme translated intents (like in [this project using the multinet script to convert intent to phoneme](https://github.com/hugobloem/esp-ha-speech)). That way, it would be independent of the user language (one would have to only select the intent files language). It could even be processed at compile time instead of runtime (the intent would be saved as phonemes after "compilation").

**Comment by synesthesiam** [comment]
@X-Ryl669 Hassil has been designed with different constraints in mind than Rhasspy: it needs to work (eventually) with all of the languages that Home Assistant supports, and it must run well in Python on a Raspberry Pi 4.

The graph search in hassil is indeed slower than other methods I've used, like openFST. There is no separate "training" step in hassil, however, and it's fairly forgiving on punctuation. Also, the intention here is not to have fuzzy matching enabled by default. Instead, fuzzy matching would only be tried if a strict match fails. And even then only a limited "budget" of edits would be used to avoid matching completely wrong text (as you mentioned).

> As far as I understand it, it seems we are making the work a lot harder by trying to match in textual world.

Absolutely :smile:  But I have yet to see a g2p system that:
1. Works **well** for all of HA's supported languages
2. Is open source with a usable license
3. Runs in real-time on a Raspberry Pi 4

**Comment by X-Ryl669** [comment]
> 3. Runs in real-time on a Raspberry Pi 4

By the time the other 2 points are completed, it won't matter much, since everyone will have Raspberry Pi 8.

**Comment by X-Ryl669** [comment]
BTW, found [this project in python](https://github.com/bootphon/phonemizer) that's wrapping the different open source phonemizer (festival, espeak-ng, mbrola, ...) for a lot of languages. Maybe it's worth adding a preprocessing step here to convert them (since HASSIL knows about the language, it should be able to call the expected function).

However, it's only part of **the perfect solution**. Because in phoneme's world, the edit distance is not the same if you match a phoneme "glyph" with any other one. For example, in English, "u" and "U" are very close, but "u" and "p" are not at all. 

So while matching the edit distance, a cross table of phoneme "edit" cost should be used. That's a symmetric matrix of (NxN) with N being the number of supported phoneme characters, that contains 0 on the diagonal and every other position should be set with the respective "sound alike" cost for that phoneme vs that other phoneme.

I'm sure someone should have done this before, but I can't figure where it is, if it's open source and public.

**Comment by tetele** [comment]
> Unlike Levenshtein, a missing phoneme or an additional phoneme in the phoneme's string is a huge penalty (there is a huge difference between **thought** => "θɔt" and **through** => "ðoʊ" but a small difference between (or **though** and **although** => "ˌɔlˈðoʊ"), so the Levenshtein algorithm shouldn't be used as this here.

The examples could have been chosen better, so as not to prove the exact opposite of what you're trying to demonstrate :P But I get your point and I think that should be a discussion. You're taking things in a very complicated place (similarity matrix etc.).

For what we need, a Levenshtein distance algorithm in the phoneme space is excellent even disregarding the similarity between them.

Thanks a lot for the `phonemizer` suggestion. I'm a bit confused about the licenses involved in `espeak-ng`, but hopefully that won't be an issue.

**Comment by synesthesiam** [comment]
The `phonemizer` project is not usable, unfortunately. From my understanding, the author has gone after other open source projects that aren't GPL for licensing issues.

**Pull request merged**
